## Travis CI Integration

notifications:
  email: false
  irc: "chat.freenode.net#d.mono-d"

language: csharp
mono: none
dotnet: 3.1.103
solution: DParser2.Unittest.sln
cache: bundler

install:
  - dotnet restore

script:
  - msbuild /p:Configuration=Debug "/p:Platform=Any CPU" DParser2.Unittest.sln
  - dotnet test ./Tests/bin/Debug/netcoreapp3.0/Tests.dll